"""empty message

Revision ID: 0ad7a6c5af71
Revises: e1f648001d09
Create Date: 2021-08-11 15:59:39.226286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad7a6c5af71'
down_revision = 'e1f648001d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('new_video', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'new_video')
    # ### end Alembic commands ###
