"""empty message

Revision ID: 5ac7422d18aa
Revises: ebdfd5457ac9
Create Date: 2021-02-28 20:03:57.911883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac7422d18aa'
down_revision = 'ebdfd5457ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isdelete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isdelete')
    # ### end Alembic commands ###
