"""empty message

Revision ID: e1f648001d09
Revises: 9f97f6b329a4
Create Date: 2021-03-12 17:43:35.199340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f648001d09'
down_revision = '9f97f6b329a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('video', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'video')
    # ### end Alembic commands ###
