"""empty message

Revision ID: e274849da0aa
Revises: 7e58616b6da1
Create Date: 2021-12-20 20:03:18.769772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e274849da0aa'
down_revision = '7e58616b6da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture_wopai_new', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('picture_jiqiu_new', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture_jiqiu_new')
    op.drop_column('user', 'picture_wopai_new')
    # ### end Alembic commands ###
