"""empty message

Revision ID: f02631405b0d
Revises: 0ad7a6c5af71
Create Date: 2021-08-12 17:06:11.637329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f02631405b0d'
down_revision = '0ad7a6c5af71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'new_video')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('new_video', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
